services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=irrigator
      - POSTGRES_USER=irrigator
      - POSTGRES_PASSWORD=irrigator12345
  backend:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=irrigator
      - POSTGRES_USER=irrigator
      - POSTGRES_PASSWORD=irrigator12345
    depends_on:
      - db
