# Generated by Django 4.0.3 on 2023-03-23 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Estates',
            },
        ),
        migrations.CreateModel(
            name='PlantationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('planting_date', models.DateField(blank=True, null=True)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('harvest_signs', models.TextField(blank=True, null=True)),
                ('is_planted', models.BooleanField(default=True)),
                ('identification', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('supply_type', models.CharField(choices=[('tank', 'tank'), ('network', 'network')], max_length=10)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_supplies', to='irrigation.estate')),
            ],
            options={
                'verbose_name_plural': 'Water supplies',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('weekdays', models.JSONField(default=[False, False, False, False, False, False, False])),
                ('hours_start', models.JSONField(default=[[], [], [], [], [], [], []])),
                ('durations', models.JSONField(default=[[0], [0], [0], [0], [0], [0], [0]])),
                ('humidity_blocker', models.BooleanField(default=False)),
                ('humidity_blocker_value', models.IntegerField(default=80)),
                ('field_plantation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='irrigation.plantationfield')),
            ],
        ),
        migrations.AddField(
            model_name='plantationfield',
            name='water_supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='field_plantations', to='irrigation.watersupply'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('field_plantation', 'is_active'), name='unique_field_active'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('field_plantation', 'name'), name='unique_field_name'),
        ),
        migrations.AlterUniqueTogether(
            name='estate',
            unique_together={('user', 'name')},
        ),
    ]
