# Generated by Django 4.0.3 on 2023-03-22 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watersupply',
            options={'verbose_name_plural': 'Water supplies'},
        ),
    ]
