# Generated by Django 4.0.3 on 2022-03-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='durations',
            field=models.JSONField(default=[[0], [0], [0], [0], [0], [0], [0]]),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='hours_start',
            field=models.JSONField(default=[[], [], [], [], [], [], []]),
        ),
    ]
