# Generated by Django 4.0.3 on 2022-03-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_alter_property_options'),
        ('irrigation', '0002_alter_schedule_durations_alter_schedule_hours_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('is_active', 'field')},
        ),
    ]
