# Generated by Django 4.0.3 on 2022-03-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0003_schedule_is_active_alter_schedule_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
