# Generated by Django 4.0.3 on 2022-11-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0004_schedule_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('field', 'is_active'), name='unique_field_active'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('field', 'name'), name='unique_field_name'),
        ),
    ]
